services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: sing-box
    network_mode: host
    restart: unless-stopped

    volumes:
      - ./config.json:/etc/sing-box/config.json:ro
      - ./certs/fullchain.pem:/etc/sing-box/cert.pem:ro
      - ./certs/privkey.pem:/etc/sing-box/key.pem:ro

    command:
      - -D
      - /var/lib/sing-box
      - -C
      - /etc/sing-box/
      - run

  xray:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./xray-config.json:/usr/local/etc/xray/config.json:ro